# Generated by Django 2.2.6 on 2022-02-19 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_auto_20220218_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita_modelo',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 21, 49, 9, 256284)),
        ),
    ]
