# Generated by Django 2.2.6 on 2022-02-19 01:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0004_auto_20220218_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita_modelo',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receita_modelo',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 18, 21, 59, 31, 385793)),
        ),
    ]
