# Generated by Django 2.2.6 on 2022-02-19 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0005_auto_20220218_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita_modelo',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receita_modelo',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 9, 54, 35, 674600)),
        ),
    ]
