# Generated by Django 2.2.6 on 2022-02-19 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0006_auto_20220219_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita_modelo',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/#m/%y/'),
        ),
        migrations.AlterField(
            model_name='receita_modelo',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 10, 52, 40, 141085)),
        ),
    ]
