# Generated by Django 2.2.6 on 2022-02-24 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0008_auto_20220224_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita_modelo',
            name='data_receita',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 24, 16, 38, 17, 338103)),
        ),
    ]
